### ISSUE TITLE
MEDIUM PRIO - Bug when filtering TIME dimension

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#3]
**POTENTIAL BUG**

**Issue:**
An md3 object with dimensions COUNTRY, VARIABLE and TIME, fails when trying to filter TIME like data[, , 1]. The others work, where 1 gets the “first”. Maybe this is a feature and not a bug, but I don't see why?

**Screenshot:**
![image](https://github.com/zeugner/MDstats/assets/114997411/06f391da-5ed3-4a33-b82f-bdbde23010c4)

**Comment by zeugner** [comment]
this should be fixed, can you test?

**Comment by tobhec** [comment]
Seem to still have the problem.
![image](https://github.com/zeugner/MDstats/assets/114997411/7a4bcc58-1dcb-4407-81c1-4f42957cbcdc)

What I did to update was run the following, and then restart RStudio. That should be sufficient right?
_source('https://s-ecfin-web.net1.cec.eu.int/directorates/db/u1/R/routines/installMDecfin.txt')_

**Comment by zeugner** [comment]
can you test the fix in teh new version, pleasE?

**Comment by tobhec** [comment]
![image](https://github.com/zeugner/MDstats/assets/114997411/ba8ca41d-d6a0-4ed6-bcd7-f61a91fa5a17)

Issue still present

**Comment by tobhec** [comment]
I just tested again after having properly updated earlier. It seems to work now indeed.

I am creating two new tickets however - One for the issue when updating via source(), and secondly an issue that seems to be related to the fix of this issue.
