### ISSUE TITLE
HIGH PRIO - Bug when renaming dimnames

### ISSUE THREAD

**Issue by tobhec** [zeugner/MDstats#4]
**BUG**

**Issue:**
When renaming dimnames, weird things happen, where a lot of data becomes NA.

**Code example:** 
`dimnames(tot_data)$VARIABLE <- c("rstr", "consdef", "pop", "nom_inc", "gfcf", "rltr", "nom_hp", "real_hp", "ptr", "pti", "npm2_nac", "housestock")`

**Screenshot**
![image](https://github.com/zeugner/MDstats/assets/114997411/5f9d7a73-c807-477c-96ff-8f011b73b5ab)

**Comment by tobhec** [comment]
The same issue seems to be present when using dimcodes instead such as in the screenshot

![image](https://github.com/zeugner/MDstats/assets/114997411/11052fd8-d0c6-4243-bc1c-9bb0e360aced)

**Comment by zeugner** [comment]
can you provide me with tot_data?

**Comment by tobhec** [comment]
Of course, I will send it to you on email.

**Comment by zeugner** [comment]
is it fixed in the new version, can you test?

**Comment by tobhec** [comment]
Problem solved! Both when using dimcodes and dimnames. Awesome!

I'll close this issue.

**Comment by tobhec** [comment]
It seems I celebrated too early. Now that I run it the old issue is back again.

**Comment by zeugner** [comment]
weird!

**Comment by tobhec** [comment]
I double checked again, controlling that I have the right version (0.1.3). Issue is still present.

**Comment by zeugner** [comment]
sthis should be fixed since version 0.1.4
